//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarajDesktop.CustomerService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="CustomerService.CustomerServiceSoap")]
    public interface CustomerServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRentalRequest", ReplyAction="*")]
        void CreateRentalRequest(int CarID, int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateRentalRequest", ReplyAction="*")]
        System.Threading.Tasks.Task CreateRentalRequestAsync(int CarID, int CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRentalRequest", ReplyAction="*")]
        void DeleteRentalRequest(int RentalRequestID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteRentalRequest", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteRentalRequestAsync(int RentalRequestID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CustomerServiceSoapChannel : CarajDesktop.CustomerService.CustomerServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CustomerServiceSoapClient : System.ServiceModel.ClientBase<CarajDesktop.CustomerService.CustomerServiceSoap>, CarajDesktop.CustomerService.CustomerServiceSoap {
        
        public CustomerServiceSoapClient() {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CustomerServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CreateRentalRequest(int CarID, int CustomerID) {
            base.Channel.CreateRentalRequest(CarID, CustomerID);
        }
        
        public System.Threading.Tasks.Task CreateRentalRequestAsync(int CarID, int CustomerID) {
            return base.Channel.CreateRentalRequestAsync(CarID, CustomerID);
        }
        
        public void DeleteRentalRequest(int RentalRequestID) {
            base.Channel.DeleteRentalRequest(RentalRequestID);
        }
        
        public System.Threading.Tasks.Task DeleteRentalRequestAsync(int RentalRequestID) {
            return base.Channel.DeleteRentalRequestAsync(RentalRequestID);
        }
    }
}
