//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarajDesktop.CarService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Car", Namespace="http://schemas.datacontract.org/2004/07/Caraj.Entities")]
    [System.SerializableAttribute()]
    public partial class Car : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> AirBagCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarBrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CarKMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarModelField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarPhotoURLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> CarPriceForRentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> CarSeatCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> CarTrunkVolumeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarajDesktop.CarService.Company CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> MaxKmPerDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> MinCustomerAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<byte> MinDrivingLicenseAgeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarajDesktop.CarService.RentDetail[] RentDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> AirBagCount {
            get {
                return this.AirBagCountField;
            }
            set {
                if ((this.AirBagCountField.Equals(value) != true)) {
                    this.AirBagCountField = value;
                    this.RaisePropertyChanged("AirBagCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarBrand {
            get {
                return this.CarBrandField;
            }
            set {
                if ((object.ReferenceEquals(this.CarBrandField, value) != true)) {
                    this.CarBrandField = value;
                    this.RaisePropertyChanged("CarBrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CarID {
            get {
                return this.CarIDField;
            }
            set {
                if ((this.CarIDField.Equals(value) != true)) {
                    this.CarIDField = value;
                    this.RaisePropertyChanged("CarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CarKM {
            get {
                return this.CarKMField;
            }
            set {
                if ((this.CarKMField.Equals(value) != true)) {
                    this.CarKMField = value;
                    this.RaisePropertyChanged("CarKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarModel {
            get {
                return this.CarModelField;
            }
            set {
                if ((object.ReferenceEquals(this.CarModelField, value) != true)) {
                    this.CarModelField = value;
                    this.RaisePropertyChanged("CarModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CarPhotoURL {
            get {
                return this.CarPhotoURLField;
            }
            set {
                if ((object.ReferenceEquals(this.CarPhotoURLField, value) != true)) {
                    this.CarPhotoURLField = value;
                    this.RaisePropertyChanged("CarPhotoURL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> CarPriceForRent {
            get {
                return this.CarPriceForRentField;
            }
            set {
                if ((this.CarPriceForRentField.Equals(value) != true)) {
                    this.CarPriceForRentField = value;
                    this.RaisePropertyChanged("CarPriceForRent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> CarSeatCount {
            get {
                return this.CarSeatCountField;
            }
            set {
                if ((this.CarSeatCountField.Equals(value) != true)) {
                    this.CarSeatCountField = value;
                    this.RaisePropertyChanged("CarSeatCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> CarTrunkVolume {
            get {
                return this.CarTrunkVolumeField;
            }
            set {
                if ((this.CarTrunkVolumeField.Equals(value) != true)) {
                    this.CarTrunkVolumeField = value;
                    this.RaisePropertyChanged("CarTrunkVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarajDesktop.CarService.Company Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MaxKmPerDay {
            get {
                return this.MaxKmPerDayField;
            }
            set {
                if ((this.MaxKmPerDayField.Equals(value) != true)) {
                    this.MaxKmPerDayField = value;
                    this.RaisePropertyChanged("MaxKmPerDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> MinCustomerAge {
            get {
                return this.MinCustomerAgeField;
            }
            set {
                if ((this.MinCustomerAgeField.Equals(value) != true)) {
                    this.MinCustomerAgeField = value;
                    this.RaisePropertyChanged("MinCustomerAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> MinDrivingLicenseAge {
            get {
                return this.MinDrivingLicenseAgeField;
            }
            set {
                if ((this.MinDrivingLicenseAgeField.Equals(value) != true)) {
                    this.MinDrivingLicenseAgeField = value;
                    this.RaisePropertyChanged("MinDrivingLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarajDesktop.CarService.RentDetail[] RentDetails {
            get {
                return this.RentDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentDetailsField, value) != true)) {
                    this.RentDetailsField = value;
                    this.RaisePropertyChanged("RentDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Company", Namespace="http://schemas.datacontract.org/2004/07/Caraj.Entities")]
    [System.SerializableAttribute()]
    public partial class Company : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarajDesktop.CarService.Car[] CarsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CompanyCarCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CompanyIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> CompanyVoteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarajDesktop.CarService.Car[] Cars {
            get {
                return this.CarsField;
            }
            set {
                if ((object.ReferenceEquals(this.CarsField, value) != true)) {
                    this.CarsField = value;
                    this.RaisePropertyChanged("Cars");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyAddress {
            get {
                return this.CompanyAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyAddressField, value) != true)) {
                    this.CompanyAddressField = value;
                    this.RaisePropertyChanged("CompanyAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CompanyCarCount {
            get {
                return this.CompanyCarCountField;
            }
            set {
                if ((this.CompanyCarCountField.Equals(value) != true)) {
                    this.CompanyCarCountField = value;
                    this.RaisePropertyChanged("CompanyCarCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CompanyPassword {
            get {
                return this.CompanyPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyPasswordField, value) != true)) {
                    this.CompanyPasswordField = value;
                    this.RaisePropertyChanged("CompanyPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> CompanyVote {
            get {
                return this.CompanyVoteField;
            }
            set {
                if ((this.CompanyVoteField.Equals(value) != true)) {
                    this.CompanyVoteField = value;
                    this.RaisePropertyChanged("CompanyVote");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RentDetail", Namespace="http://schemas.datacontract.org/2004/07/Caraj.Entities")]
    [System.SerializableAttribute()]
    public partial class RentDetail : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarajDesktop.CarService.Car CarField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarajDesktop.CarService.Customer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> EndingKilometerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> PricingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RentDetailIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RentEndDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> RentStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> StartingKilometerField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarajDesktop.CarService.Car Car {
            get {
                return this.CarField;
            }
            set {
                if ((object.ReferenceEquals(this.CarField, value) != true)) {
                    this.CarField = value;
                    this.RaisePropertyChanged("Car");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CarID {
            get {
                return this.CarIDField;
            }
            set {
                if ((this.CarIDField.Equals(value) != true)) {
                    this.CarIDField = value;
                    this.RaisePropertyChanged("CarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarajDesktop.CarService.Customer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> EndingKilometer {
            get {
                return this.EndingKilometerField;
            }
            set {
                if ((this.EndingKilometerField.Equals(value) != true)) {
                    this.EndingKilometerField = value;
                    this.RaisePropertyChanged("EndingKilometer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Pricing {
            get {
                return this.PricingField;
            }
            set {
                if ((this.PricingField.Equals(value) != true)) {
                    this.PricingField = value;
                    this.RaisePropertyChanged("Pricing");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RentDetailID {
            get {
                return this.RentDetailIDField;
            }
            set {
                if ((this.RentDetailIDField.Equals(value) != true)) {
                    this.RentDetailIDField = value;
                    this.RaisePropertyChanged("RentDetailID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RentEndDate {
            get {
                return this.RentEndDateField;
            }
            set {
                if ((this.RentEndDateField.Equals(value) != true)) {
                    this.RentEndDateField = value;
                    this.RaisePropertyChanged("RentEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> RentStartDate {
            get {
                return this.RentStartDateField;
            }
            set {
                if ((this.RentStartDateField.Equals(value) != true)) {
                    this.RentStartDateField = value;
                    this.RaisePropertyChanged("RentStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> StartingKilometer {
            get {
                return this.StartingKilometerField;
            }
            set {
                if ((this.StartingKilometerField.Equals(value) != true)) {
                    this.StartingKilometerField = value;
                    this.RaisePropertyChanged("StartingKilometer");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://schemas.datacontract.org/2004/07/Caraj.Entities")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CustomerBirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerPasswordField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerSurnameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private CarajDesktop.CarService.RentDetail[] RentDetailsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CustomerBirthDate {
            get {
                return this.CustomerBirthDateField;
            }
            set {
                if ((this.CustomerBirthDateField.Equals(value) != true)) {
                    this.CustomerBirthDateField = value;
                    this.RaisePropertyChanged("CustomerBirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID {
            get {
                return this.CustomerIDField;
            }
            set {
                if ((this.CustomerIDField.Equals(value) != true)) {
                    this.CustomerIDField = value;
                    this.RaisePropertyChanged("CustomerID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerPassword {
            get {
                return this.CustomerPasswordField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerPasswordField, value) != true)) {
                    this.CustomerPasswordField = value;
                    this.RaisePropertyChanged("CustomerPassword");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerSurname {
            get {
                return this.CustomerSurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerSurnameField, value) != true)) {
                    this.CustomerSurnameField = value;
                    this.RaisePropertyChanged("CustomerSurname");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerUserName {
            get {
                return this.CustomerUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerUserNameField, value) != true)) {
                    this.CustomerUserNameField = value;
                    this.RaisePropertyChanged("CustomerUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CarajDesktop.CarService.RentDetail[] RentDetails {
            get {
                return this.RentDetailsField;
            }
            set {
                if ((object.ReferenceEquals(this.RentDetailsField, value) != true)) {
                    this.RentDetailsField = value;
                    this.RaisePropertyChanged("RentDetails");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CarService.ICarService")]
    public interface ICarService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetAvailableCar", ReplyAction="http://tempuri.org/ICarService/GetAvailableCarResponse")]
        CarajDesktop.CarService.Car[] GetAvailableCar(System.DateTime first, System.DateTime last);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/GetAvailableCar", ReplyAction="http://tempuri.org/ICarService/GetAvailableCarResponse")]
        System.Threading.Tasks.Task<CarajDesktop.CarService.Car[]> GetAvailableCarAsync(System.DateTime first, System.DateTime last);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/Sayi", ReplyAction="http://tempuri.org/ICarService/SayiResponse")]
        int Sayi();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICarService/Sayi", ReplyAction="http://tempuri.org/ICarService/SayiResponse")]
        System.Threading.Tasks.Task<int> SayiAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICarServiceChannel : CarajDesktop.CarService.ICarService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarServiceClient : System.ServiceModel.ClientBase<CarajDesktop.CarService.ICarService>, CarajDesktop.CarService.ICarService {
        
        public CarServiceClient() {
        }
        
        public CarServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public CarajDesktop.CarService.Car[] GetAvailableCar(System.DateTime first, System.DateTime last) {
            return base.Channel.GetAvailableCar(first, last);
        }
        
        public System.Threading.Tasks.Task<CarajDesktop.CarService.Car[]> GetAvailableCarAsync(System.DateTime first, System.DateTime last) {
            return base.Channel.GetAvailableCarAsync(first, last);
        }
        
        public int Sayi() {
            return base.Channel.Sayi();
        }
        
        public System.Threading.Tasks.Task<int> SayiAsync() {
            return base.Channel.SayiAsync();
        }
    }
}
