//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarajDesktop.CarService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarReturnDto", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    public partial class CarReturnDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CarIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyAddressField;
        
        private double CompanyVoteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarBrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarModelField;
        
        private byte MinDrivingLicenseAgeField;
        
        private byte MinCustomerAgeField;
        
        private int MaxKmPerDayField;
        
        private int CarKMField;
        
        private byte AirBagCountField;
        
        private short CarTrunkVolumeField;
        
        private byte CarSeatCountField;
        
        private decimal CarPriceForRentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarPhotoURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int CarID {
            get {
                return this.CarIDField;
            }
            set {
                if ((this.CarIDField.Equals(value) != true)) {
                    this.CarIDField = value;
                    this.RaisePropertyChanged("CarID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CompanyAddress {
            get {
                return this.CompanyAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyAddressField, value) != true)) {
                    this.CompanyAddressField = value;
                    this.RaisePropertyChanged("CompanyAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public double CompanyVote {
            get {
                return this.CompanyVoteField;
            }
            set {
                if ((this.CompanyVoteField.Equals(value) != true)) {
                    this.CompanyVoteField = value;
                    this.RaisePropertyChanged("CompanyVote");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CarBrand {
            get {
                return this.CarBrandField;
            }
            set {
                if ((object.ReferenceEquals(this.CarBrandField, value) != true)) {
                    this.CarBrandField = value;
                    this.RaisePropertyChanged("CarBrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CarModel {
            get {
                return this.CarModelField;
            }
            set {
                if ((object.ReferenceEquals(this.CarModelField, value) != true)) {
                    this.CarModelField = value;
                    this.RaisePropertyChanged("CarModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public byte MinDrivingLicenseAge {
            get {
                return this.MinDrivingLicenseAgeField;
            }
            set {
                if ((this.MinDrivingLicenseAgeField.Equals(value) != true)) {
                    this.MinDrivingLicenseAgeField = value;
                    this.RaisePropertyChanged("MinDrivingLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public byte MinCustomerAge {
            get {
                return this.MinCustomerAgeField;
            }
            set {
                if ((this.MinCustomerAgeField.Equals(value) != true)) {
                    this.MinCustomerAgeField = value;
                    this.RaisePropertyChanged("MinCustomerAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int MaxKmPerDay {
            get {
                return this.MaxKmPerDayField;
            }
            set {
                if ((this.MaxKmPerDayField.Equals(value) != true)) {
                    this.MaxKmPerDayField = value;
                    this.RaisePropertyChanged("MaxKmPerDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int CarKM {
            get {
                return this.CarKMField;
            }
            set {
                if ((this.CarKMField.Equals(value) != true)) {
                    this.CarKMField = value;
                    this.RaisePropertyChanged("CarKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public byte AirBagCount {
            get {
                return this.AirBagCountField;
            }
            set {
                if ((this.AirBagCountField.Equals(value) != true)) {
                    this.AirBagCountField = value;
                    this.RaisePropertyChanged("AirBagCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public short CarTrunkVolume {
            get {
                return this.CarTrunkVolumeField;
            }
            set {
                if ((this.CarTrunkVolumeField.Equals(value) != true)) {
                    this.CarTrunkVolumeField = value;
                    this.RaisePropertyChanged("CarTrunkVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=12)]
        public byte CarSeatCount {
            get {
                return this.CarSeatCountField;
            }
            set {
                if ((this.CarSeatCountField.Equals(value) != true)) {
                    this.CarSeatCountField = value;
                    this.RaisePropertyChanged("CarSeatCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=13)]
        public decimal CarPriceForRent {
            get {
                return this.CarPriceForRentField;
            }
            set {
                if ((this.CarPriceForRentField.Equals(value) != true)) {
                    this.CarPriceForRentField = value;
                    this.RaisePropertyChanged("CarPriceForRent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=14)]
        public string CarPhotoURL {
            get {
                return this.CarPhotoURLField;
            }
            set {
                if ((object.ReferenceEquals(this.CarPhotoURLField, value) != true)) {
                    this.CarPhotoURLField = value;
                    this.RaisePropertyChanged("CarPhotoURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarRequestDto", Namespace="http://tempuri.org")]
    [System.SerializableAttribute()]
    public partial class CarRequestDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarBrandField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarModelField;
        
        private byte MinDrivingLicenseAgeField;
        
        private byte MinCustomerAgeField;
        
        private int MaxKmPerDayField;
        
        private int CarKMField;
        
        private byte AirBagCountField;
        
        private short CarTrunkVolumeField;
        
        private byte CarSeatCountField;
        
        private decimal CarPriceForRentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CarPhotoURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CarBrand {
            get {
                return this.CarBrandField;
            }
            set {
                if ((object.ReferenceEquals(this.CarBrandField, value) != true)) {
                    this.CarBrandField = value;
                    this.RaisePropertyChanged("CarBrand");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string CarModel {
            get {
                return this.CarModelField;
            }
            set {
                if ((object.ReferenceEquals(this.CarModelField, value) != true)) {
                    this.CarModelField = value;
                    this.RaisePropertyChanged("CarModel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public byte MinDrivingLicenseAge {
            get {
                return this.MinDrivingLicenseAgeField;
            }
            set {
                if ((this.MinDrivingLicenseAgeField.Equals(value) != true)) {
                    this.MinDrivingLicenseAgeField = value;
                    this.RaisePropertyChanged("MinDrivingLicenseAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public byte MinCustomerAge {
            get {
                return this.MinCustomerAgeField;
            }
            set {
                if ((this.MinCustomerAgeField.Equals(value) != true)) {
                    this.MinCustomerAgeField = value;
                    this.RaisePropertyChanged("MinCustomerAge");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int MaxKmPerDay {
            get {
                return this.MaxKmPerDayField;
            }
            set {
                if ((this.MaxKmPerDayField.Equals(value) != true)) {
                    this.MaxKmPerDayField = value;
                    this.RaisePropertyChanged("MaxKmPerDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public int CarKM {
            get {
                return this.CarKMField;
            }
            set {
                if ((this.CarKMField.Equals(value) != true)) {
                    this.CarKMField = value;
                    this.RaisePropertyChanged("CarKM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public byte AirBagCount {
            get {
                return this.AirBagCountField;
            }
            set {
                if ((this.AirBagCountField.Equals(value) != true)) {
                    this.AirBagCountField = value;
                    this.RaisePropertyChanged("AirBagCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public short CarTrunkVolume {
            get {
                return this.CarTrunkVolumeField;
            }
            set {
                if ((this.CarTrunkVolumeField.Equals(value) != true)) {
                    this.CarTrunkVolumeField = value;
                    this.RaisePropertyChanged("CarTrunkVolume");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public byte CarSeatCount {
            get {
                return this.CarSeatCountField;
            }
            set {
                if ((this.CarSeatCountField.Equals(value) != true)) {
                    this.CarSeatCountField = value;
                    this.RaisePropertyChanged("CarSeatCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public decimal CarPriceForRent {
            get {
                return this.CarPriceForRentField;
            }
            set {
                if ((this.CarPriceForRentField.Equals(value) != true)) {
                    this.CarPriceForRentField = value;
                    this.RaisePropertyChanged("CarPriceForRent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string CarPhotoURL {
            get {
                return this.CarPhotoURLField;
            }
            set {
                if ((object.ReferenceEquals(this.CarPhotoURLField, value) != true)) {
                    this.CarPhotoURLField = value;
                    this.RaisePropertyChanged("CarPhotoURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="CarService.CarServiceSoap")]
    public interface CarServiceSoap {
        
        // CODEGEN: Generating message contract since element name GetAvailableCarResult from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableCar", ReplyAction="*")]
        CarajDesktop.CarService.GetAvailableCarResponse GetAvailableCar(CarajDesktop.CarService.GetAvailableCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableCar", ReplyAction="*")]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetAvailableCarResponse> GetAvailableCarAsync(CarajDesktop.CarService.GetAvailableCarRequest request);
        
        // CODEGEN: Generating message contract since element name GetAvailableCarByCompanyIDResult from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableCarByCompanyID", ReplyAction="*")]
        CarajDesktop.CarService.GetAvailableCarByCompanyIDResponse GetAvailableCarByCompanyID(CarajDesktop.CarService.GetAvailableCarByCompanyIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAvailableCarByCompanyID", ReplyAction="*")]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetAvailableCarByCompanyIDResponse> GetAvailableCarByCompanyIDAsync(CarajDesktop.CarService.GetAvailableCarByCompanyIDRequest request);
        
        // CODEGEN: Generating message contract since element name GetCarsResult from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCars", ReplyAction="*")]
        CarajDesktop.CarService.GetCarsResponse GetCars(CarajDesktop.CarService.GetCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCars", ReplyAction="*")]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetCarsResponse> GetCarsAsync(CarajDesktop.CarService.GetCarsRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllCarsResult from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCars", ReplyAction="*")]
        CarajDesktop.CarService.GetAllCarsResponse GetAllCars(CarajDesktop.CarService.GetAllCarsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCars", ReplyAction="*")]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetAllCarsResponse> GetAllCarsAsync(CarajDesktop.CarService.GetAllCarsRequest request);
        
        // CODEGEN: Generating message contract since element name GetCarResult from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCar", ReplyAction="*")]
        CarajDesktop.CarService.GetCarResponse GetCar(CarajDesktop.CarService.GetCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCar", ReplyAction="*")]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetCarResponse> GetCarAsync(CarajDesktop.CarService.GetCarRequest request);
        
        // CODEGEN: Generating message contract since element name model from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCar", ReplyAction="*")]
        CarajDesktop.CarService.AddCarResponse AddCar(CarajDesktop.CarService.AddCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddCar", ReplyAction="*")]
        System.Threading.Tasks.Task<CarajDesktop.CarService.AddCarResponse> AddCarAsync(CarajDesktop.CarService.AddCarRequest request);
        
        // CODEGEN: Generating message contract since element name model from namespace http://tempuri.org is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCar", ReplyAction="*")]
        CarajDesktop.CarService.UpdateCarResponse UpdateCar(CarajDesktop.CarService.UpdateCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateCar", ReplyAction="*")]
        System.Threading.Tasks.Task<CarajDesktop.CarService.UpdateCarResponse> UpdateCarAsync(CarajDesktop.CarService.UpdateCarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCar", ReplyAction="*")]
        void DeleteCar(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteCar", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteCarAsync(int id);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableCar", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetAvailableCarRequestBody Body;
        
        public GetAvailableCarRequest() {
        }
        
        public GetAvailableCarRequest(CarajDesktop.CarService.GetAvailableCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetAvailableCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime first;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime last;
        
        public GetAvailableCarRequestBody() {
        }
        
        public GetAvailableCarRequestBody(System.DateTime first, System.DateTime last) {
            this.first = first;
            this.last = last;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableCarResponse", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetAvailableCarResponseBody Body;
        
        public GetAvailableCarResponse() {
        }
        
        public GetAvailableCarResponse(CarajDesktop.CarService.GetAvailableCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetAvailableCarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarajDesktop.CarService.CarReturnDto[] GetAvailableCarResult;
        
        public GetAvailableCarResponseBody() {
        }
        
        public GetAvailableCarResponseBody(CarajDesktop.CarService.CarReturnDto[] GetAvailableCarResult) {
            this.GetAvailableCarResult = GetAvailableCarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableCarByCompanyIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableCarByCompanyID", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetAvailableCarByCompanyIDRequestBody Body;
        
        public GetAvailableCarByCompanyIDRequest() {
        }
        
        public GetAvailableCarByCompanyIDRequest(CarajDesktop.CarService.GetAvailableCarByCompanyIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetAvailableCarByCompanyIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public System.DateTime first;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime last;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int CompanyID;
        
        public GetAvailableCarByCompanyIDRequestBody() {
        }
        
        public GetAvailableCarByCompanyIDRequestBody(System.DateTime first, System.DateTime last, int CompanyID) {
            this.first = first;
            this.last = last;
            this.CompanyID = CompanyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAvailableCarByCompanyIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAvailableCarByCompanyIDResponse", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetAvailableCarByCompanyIDResponseBody Body;
        
        public GetAvailableCarByCompanyIDResponse() {
        }
        
        public GetAvailableCarByCompanyIDResponse(CarajDesktop.CarService.GetAvailableCarByCompanyIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetAvailableCarByCompanyIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarajDesktop.CarService.CarReturnDto[] GetAvailableCarByCompanyIDResult;
        
        public GetAvailableCarByCompanyIDResponseBody() {
        }
        
        public GetAvailableCarByCompanyIDResponseBody(CarajDesktop.CarService.CarReturnDto[] GetAvailableCarByCompanyIDResult) {
            this.GetAvailableCarByCompanyIDResult = GetAvailableCarByCompanyIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCars", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetCarsRequestBody Body;
        
        public GetCarsRequest() {
        }
        
        public GetCarsRequest(CarajDesktop.CarService.GetCarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetCarsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCarsRequestBody() {
        }
        
        public GetCarsRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarsResponse", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetCarsResponseBody Body;
        
        public GetCarsResponse() {
        }
        
        public GetCarsResponse(CarajDesktop.CarService.GetCarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetCarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarajDesktop.CarService.CarReturnDto[] GetCarsResult;
        
        public GetCarsResponseBody() {
        }
        
        public GetCarsResponseBody(CarajDesktop.CarService.CarReturnDto[] GetCarsResult) {
            this.GetCarsResult = GetCarsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCarsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCars", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetAllCarsRequestBody Body;
        
        public GetAllCarsRequest() {
        }
        
        public GetAllCarsRequest(CarajDesktop.CarService.GetAllCarsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCarsRequestBody {
        
        public GetAllCarsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCarsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCarsResponse", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetAllCarsResponseBody Body;
        
        public GetAllCarsResponse() {
        }
        
        public GetAllCarsResponse(CarajDesktop.CarService.GetAllCarsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetAllCarsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarajDesktop.CarService.CarReturnDto[] GetAllCarsResult;
        
        public GetAllCarsResponseBody() {
        }
        
        public GetAllCarsResponseBody(CarajDesktop.CarService.CarReturnDto[] GetAllCarsResult) {
            this.GetAllCarsResult = GetAllCarsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCar", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetCarRequestBody Body;
        
        public GetCarRequest() {
        }
        
        public GetCarRequest(CarajDesktop.CarService.GetCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetCarRequestBody() {
        }
        
        public GetCarRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCarResponse", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.GetCarResponseBody Body;
        
        public GetCarResponse() {
        }
        
        public GetCarResponse(CarajDesktop.CarService.GetCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class GetCarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarajDesktop.CarService.CarReturnDto GetCarResult;
        
        public GetCarResponseBody() {
        }
        
        public GetCarResponseBody(CarajDesktop.CarService.CarReturnDto GetCarResult) {
            this.GetCarResult = GetCarResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCar", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.AddCarRequestBody Body;
        
        public AddCarRequest() {
        }
        
        public AddCarRequest(CarajDesktop.CarService.AddCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class AddCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarajDesktop.CarService.CarRequestDto model;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CompanyID;
        
        public AddCarRequestBody() {
        }
        
        public AddCarRequestBody(CarajDesktop.CarService.CarRequestDto model, int CompanyID) {
            this.model = model;
            this.CompanyID = CompanyID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddCarResponse", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.AddCarResponseBody Body;
        
        public AddCarResponse() {
        }
        
        public AddCarResponse(CarajDesktop.CarService.AddCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AddCarResponseBody {
        
        public AddCarResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCar", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.UpdateCarRequestBody Body;
        
        public UpdateCarRequest() {
        }
        
        public UpdateCarRequest(CarajDesktop.CarService.UpdateCarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org")]
    public partial class UpdateCarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CarajDesktop.CarService.CarRequestDto model;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int CarID;
        
        public UpdateCarRequestBody() {
        }
        
        public UpdateCarRequestBody(CarajDesktop.CarService.CarRequestDto model, int CarID) {
            this.model = model;
            this.CarID = CarID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateCarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateCarResponse", Namespace="http://tempuri.org", Order=0)]
        public CarajDesktop.CarService.UpdateCarResponseBody Body;
        
        public UpdateCarResponse() {
        }
        
        public UpdateCarResponse(CarajDesktop.CarService.UpdateCarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UpdateCarResponseBody {
        
        public UpdateCarResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CarServiceSoapChannel : CarajDesktop.CarService.CarServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CarServiceSoapClient : System.ServiceModel.ClientBase<CarajDesktop.CarService.CarServiceSoap>, CarajDesktop.CarService.CarServiceSoap {
        
        public CarServiceSoapClient() {
        }
        
        public CarServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CarServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CarServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarajDesktop.CarService.GetAvailableCarResponse CarajDesktop.CarService.CarServiceSoap.GetAvailableCar(CarajDesktop.CarService.GetAvailableCarRequest request) {
            return base.Channel.GetAvailableCar(request);
        }
        
        public CarajDesktop.CarService.CarReturnDto[] GetAvailableCar(System.DateTime first, System.DateTime last) {
            CarajDesktop.CarService.GetAvailableCarRequest inValue = new CarajDesktop.CarService.GetAvailableCarRequest();
            inValue.Body = new CarajDesktop.CarService.GetAvailableCarRequestBody();
            inValue.Body.first = first;
            inValue.Body.last = last;
            CarajDesktop.CarService.GetAvailableCarResponse retVal = ((CarajDesktop.CarService.CarServiceSoap)(this)).GetAvailableCar(inValue);
            return retVal.Body.GetAvailableCarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetAvailableCarResponse> CarajDesktop.CarService.CarServiceSoap.GetAvailableCarAsync(CarajDesktop.CarService.GetAvailableCarRequest request) {
            return base.Channel.GetAvailableCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarajDesktop.CarService.GetAvailableCarResponse> GetAvailableCarAsync(System.DateTime first, System.DateTime last) {
            CarajDesktop.CarService.GetAvailableCarRequest inValue = new CarajDesktop.CarService.GetAvailableCarRequest();
            inValue.Body = new CarajDesktop.CarService.GetAvailableCarRequestBody();
            inValue.Body.first = first;
            inValue.Body.last = last;
            return ((CarajDesktop.CarService.CarServiceSoap)(this)).GetAvailableCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarajDesktop.CarService.GetAvailableCarByCompanyIDResponse CarajDesktop.CarService.CarServiceSoap.GetAvailableCarByCompanyID(CarajDesktop.CarService.GetAvailableCarByCompanyIDRequest request) {
            return base.Channel.GetAvailableCarByCompanyID(request);
        }
        
        public CarajDesktop.CarService.CarReturnDto[] GetAvailableCarByCompanyID(System.DateTime first, System.DateTime last, int CompanyID) {
            CarajDesktop.CarService.GetAvailableCarByCompanyIDRequest inValue = new CarajDesktop.CarService.GetAvailableCarByCompanyIDRequest();
            inValue.Body = new CarajDesktop.CarService.GetAvailableCarByCompanyIDRequestBody();
            inValue.Body.first = first;
            inValue.Body.last = last;
            inValue.Body.CompanyID = CompanyID;
            CarajDesktop.CarService.GetAvailableCarByCompanyIDResponse retVal = ((CarajDesktop.CarService.CarServiceSoap)(this)).GetAvailableCarByCompanyID(inValue);
            return retVal.Body.GetAvailableCarByCompanyIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetAvailableCarByCompanyIDResponse> CarajDesktop.CarService.CarServiceSoap.GetAvailableCarByCompanyIDAsync(CarajDesktop.CarService.GetAvailableCarByCompanyIDRequest request) {
            return base.Channel.GetAvailableCarByCompanyIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarajDesktop.CarService.GetAvailableCarByCompanyIDResponse> GetAvailableCarByCompanyIDAsync(System.DateTime first, System.DateTime last, int CompanyID) {
            CarajDesktop.CarService.GetAvailableCarByCompanyIDRequest inValue = new CarajDesktop.CarService.GetAvailableCarByCompanyIDRequest();
            inValue.Body = new CarajDesktop.CarService.GetAvailableCarByCompanyIDRequestBody();
            inValue.Body.first = first;
            inValue.Body.last = last;
            inValue.Body.CompanyID = CompanyID;
            return ((CarajDesktop.CarService.CarServiceSoap)(this)).GetAvailableCarByCompanyIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarajDesktop.CarService.GetCarsResponse CarajDesktop.CarService.CarServiceSoap.GetCars(CarajDesktop.CarService.GetCarsRequest request) {
            return base.Channel.GetCars(request);
        }
        
        public CarajDesktop.CarService.CarReturnDto[] GetCars(int id) {
            CarajDesktop.CarService.GetCarsRequest inValue = new CarajDesktop.CarService.GetCarsRequest();
            inValue.Body = new CarajDesktop.CarService.GetCarsRequestBody();
            inValue.Body.id = id;
            CarajDesktop.CarService.GetCarsResponse retVal = ((CarajDesktop.CarService.CarServiceSoap)(this)).GetCars(inValue);
            return retVal.Body.GetCarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetCarsResponse> CarajDesktop.CarService.CarServiceSoap.GetCarsAsync(CarajDesktop.CarService.GetCarsRequest request) {
            return base.Channel.GetCarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarajDesktop.CarService.GetCarsResponse> GetCarsAsync(int id) {
            CarajDesktop.CarService.GetCarsRequest inValue = new CarajDesktop.CarService.GetCarsRequest();
            inValue.Body = new CarajDesktop.CarService.GetCarsRequestBody();
            inValue.Body.id = id;
            return ((CarajDesktop.CarService.CarServiceSoap)(this)).GetCarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarajDesktop.CarService.GetAllCarsResponse CarajDesktop.CarService.CarServiceSoap.GetAllCars(CarajDesktop.CarService.GetAllCarsRequest request) {
            return base.Channel.GetAllCars(request);
        }
        
        public CarajDesktop.CarService.CarReturnDto[] GetAllCars() {
            CarajDesktop.CarService.GetAllCarsRequest inValue = new CarajDesktop.CarService.GetAllCarsRequest();
            inValue.Body = new CarajDesktop.CarService.GetAllCarsRequestBody();
            CarajDesktop.CarService.GetAllCarsResponse retVal = ((CarajDesktop.CarService.CarServiceSoap)(this)).GetAllCars(inValue);
            return retVal.Body.GetAllCarsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetAllCarsResponse> CarajDesktop.CarService.CarServiceSoap.GetAllCarsAsync(CarajDesktop.CarService.GetAllCarsRequest request) {
            return base.Channel.GetAllCarsAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarajDesktop.CarService.GetAllCarsResponse> GetAllCarsAsync() {
            CarajDesktop.CarService.GetAllCarsRequest inValue = new CarajDesktop.CarService.GetAllCarsRequest();
            inValue.Body = new CarajDesktop.CarService.GetAllCarsRequestBody();
            return ((CarajDesktop.CarService.CarServiceSoap)(this)).GetAllCarsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarajDesktop.CarService.GetCarResponse CarajDesktop.CarService.CarServiceSoap.GetCar(CarajDesktop.CarService.GetCarRequest request) {
            return base.Channel.GetCar(request);
        }
        
        public CarajDesktop.CarService.CarReturnDto GetCar(int id) {
            CarajDesktop.CarService.GetCarRequest inValue = new CarajDesktop.CarService.GetCarRequest();
            inValue.Body = new CarajDesktop.CarService.GetCarRequestBody();
            inValue.Body.id = id;
            CarajDesktop.CarService.GetCarResponse retVal = ((CarajDesktop.CarService.CarServiceSoap)(this)).GetCar(inValue);
            return retVal.Body.GetCarResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarajDesktop.CarService.GetCarResponse> CarajDesktop.CarService.CarServiceSoap.GetCarAsync(CarajDesktop.CarService.GetCarRequest request) {
            return base.Channel.GetCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarajDesktop.CarService.GetCarResponse> GetCarAsync(int id) {
            CarajDesktop.CarService.GetCarRequest inValue = new CarajDesktop.CarService.GetCarRequest();
            inValue.Body = new CarajDesktop.CarService.GetCarRequestBody();
            inValue.Body.id = id;
            return ((CarajDesktop.CarService.CarServiceSoap)(this)).GetCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarajDesktop.CarService.AddCarResponse CarajDesktop.CarService.CarServiceSoap.AddCar(CarajDesktop.CarService.AddCarRequest request) {
            return base.Channel.AddCar(request);
        }
        
        public void AddCar(CarajDesktop.CarService.CarRequestDto model, int CompanyID) {
            CarajDesktop.CarService.AddCarRequest inValue = new CarajDesktop.CarService.AddCarRequest();
            inValue.Body = new CarajDesktop.CarService.AddCarRequestBody();
            inValue.Body.model = model;
            inValue.Body.CompanyID = CompanyID;
            CarajDesktop.CarService.AddCarResponse retVal = ((CarajDesktop.CarService.CarServiceSoap)(this)).AddCar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarajDesktop.CarService.AddCarResponse> CarajDesktop.CarService.CarServiceSoap.AddCarAsync(CarajDesktop.CarService.AddCarRequest request) {
            return base.Channel.AddCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarajDesktop.CarService.AddCarResponse> AddCarAsync(CarajDesktop.CarService.CarRequestDto model, int CompanyID) {
            CarajDesktop.CarService.AddCarRequest inValue = new CarajDesktop.CarService.AddCarRequest();
            inValue.Body = new CarajDesktop.CarService.AddCarRequestBody();
            inValue.Body.model = model;
            inValue.Body.CompanyID = CompanyID;
            return ((CarajDesktop.CarService.CarServiceSoap)(this)).AddCarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CarajDesktop.CarService.UpdateCarResponse CarajDesktop.CarService.CarServiceSoap.UpdateCar(CarajDesktop.CarService.UpdateCarRequest request) {
            return base.Channel.UpdateCar(request);
        }
        
        public void UpdateCar(CarajDesktop.CarService.CarRequestDto model, int CarID) {
            CarajDesktop.CarService.UpdateCarRequest inValue = new CarajDesktop.CarService.UpdateCarRequest();
            inValue.Body = new CarajDesktop.CarService.UpdateCarRequestBody();
            inValue.Body.model = model;
            inValue.Body.CarID = CarID;
            CarajDesktop.CarService.UpdateCarResponse retVal = ((CarajDesktop.CarService.CarServiceSoap)(this)).UpdateCar(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CarajDesktop.CarService.UpdateCarResponse> CarajDesktop.CarService.CarServiceSoap.UpdateCarAsync(CarajDesktop.CarService.UpdateCarRequest request) {
            return base.Channel.UpdateCarAsync(request);
        }
        
        public System.Threading.Tasks.Task<CarajDesktop.CarService.UpdateCarResponse> UpdateCarAsync(CarajDesktop.CarService.CarRequestDto model, int CarID) {
            CarajDesktop.CarService.UpdateCarRequest inValue = new CarajDesktop.CarService.UpdateCarRequest();
            inValue.Body = new CarajDesktop.CarService.UpdateCarRequestBody();
            inValue.Body.model = model;
            inValue.Body.CarID = CarID;
            return ((CarajDesktop.CarService.CarServiceSoap)(this)).UpdateCarAsync(inValue);
        }
        
        public void DeleteCar(int id) {
            base.Channel.DeleteCar(id);
        }
        
        public System.Threading.Tasks.Task DeleteCarAsync(int id) {
            return base.Channel.DeleteCarAsync(id);
        }
    }
}
